### ISSUE TITLE
Resistors: Should I use any on my buttons?

### ISSUE THREAD

**Issue by fedekrum** [mholgatem/GPIOnext#27]
Hi,
I am actually using GPIONext without resistors in my buttons. They are directly connected.
Should I use any on my buttons and joystick?

My GPIONext config for "gpionext set pulldown" is as default  [false] .
Thanks !!

**Comment by mholgatem** [comment]
You don't really need them. The pi already has builtin 50k resistors, so unless you have really long wires connecting your pi to your buttons (which could pick up stray radio signals and interpret them as button presses), I wouldn't bother.

If it's because you are worried about shorting the pi, I wouldn't worry too much. The pi has a polyfuse that protects it. If you do something really wrong, the polyfuse will overheat and turn off your pi. In which case, you just have to wait for it to cool down and then the raspberry pi will work again.
