### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by boquetipo** [mholgatem/GPIOnext#4]
Hi,
Somehow the script is working, but I had some installation issues, so I would like to share my complete experience here. I don't know if this can be classified as an issue 'per se'.

1. I had gpioneer previously, but I never tested properly because I'm trying to build a GBZ, and it's really hard to me.
2. I removed gpioneer with remove.sh script. It said there weren't installed several packages, but I didn't mind. I don't have a clue about unix.
3. I installed gpionext script and run installer with bash. At some point, the rpi0 rebooted continously after 15 s running. So I had to make a new retropie installation.
4. After I configured wifi, etc, again, I installed gpionext script again and run the installation with bash. This time I had error conections with jessie repository. The installation finished and the script asked if I want to run configuration. I said 'yes' but I had en error about a missing package (or similar, I don't remember).
5. I run the installer a second time, and failed again but later than the first one. Configuration still failed.
6. I run the installer a third time, and apparently nothing failed. The configuration run fine and I could configure the buttons. Nice menu by the way.
7. I run ES and it detected the "gamepad" and could configure all buttons.

Thanks to the author. Now I'm closer to finish my GBZ.

**Comment by mholgatem** [comment]
So there is a problem with the mirrordirector right now ( I was having a heck of a time with a different project). That is what caused problems 3, 4, & 5. I'm not sure what is causing it, but it is on the server side, not our side. 

In the future, if you run into a problem trying to install a package you can [edit your sources list to specify a particular mirror, instead of letting the mirrordirector handle it. ](https://raspberrypi.stackexchange.com/questions/27479/cannot-connect-to-mirrordirector-raspbian)
