### ISSUE TITLE
retropi thinks i have joystick 3 and 4

### ISSUE THREAD

**Issue by skulldy** [mholgatem/GPIOnext#50]
I removed mk-arcade-joystick from the dkms tree and installed gpionext and configured. It works fine but retropi thinks i'm using joysticks 3 and 4. Am I doing something wrong ?

**Comment by mholgatem** [comment]
It's probably seeing other peripherals that are plugged in (keyboard/mouse/etc.) before it sees the GPIOnext controls. I believe that there is a config file that you can edit in retropie to assign controllers. It's been a while since I've messed with any of that stuff, so that's about all the help I can offer.
