### ISSUE TITLE
NO GAMPADS DETECTED

### ISSUE THREAD

**Issue by bobskos** [mholgatem/GPIOnext#53]
I've gotten it to detect a game pad tons of times but all of the sudden after I configure some more buttons it just doesn't detect a game pad anymore

**Comment by bobskos** [comment]
I figured it out!

**Comment by bobskos** [comment]
- [ ]

**Comment by merwok** [comment]
Can you share what the problem and solution were?

**Comment by bobskos** [comment]
The problem was that retropie wasn't recognizing my buttons anymore. I think what solved it was that that before I only had 4 buttons because I was testing out a d-pad I made and it didn't work. But after that I added a few more buttons and it worked fine.

**Comment by mholgatem** [comment]
retropie has some arbitrary requirements for what it will recognize as a controller. It's something like it needs at least 1 directional pad and 2 buttons. Otherwise it won't recognize it. You can get around this (for testing purposes) by using gpionext and setting up a virtual keyboard assigned to your controller. retropie will always recognize that.
