### ISSUE TITLE
Only two inputs work

### ISSUE THREAD

**Issue by Riky568** [mholgatem/GPIOnext#78]
This happened with both my arudino joy stick, and a PSP thumbstick I wired myself. For some reason when I try and set an input, only "up" and "left" register.

**Comment by Riky568** [comment]
Sure. Let me know if these are good enough.

**Comment by mholgatem** [comment]
it looks like you are using something like this: https://www.adafruit.com/product/444
Those won't work with the raspberry pi since it only has digital gpio pins and those are analog.

if you have an arduino that uses the atmega32u4 chip (such as the micro), you can use those joysticks on its analog pins and then configure it to act as an hid device.

**Comment by Riky568** [comment]
Got it. Thank you so much.
